rosbag record \
/os_cloud_node/points \
/scout/mavros/imu/data \
/BLIO/odom_gicp_global_prediction \
/BLIO/Globalmap \
/BLIO/Localmap \
/BLIO/Keyframe \
/BLIO/KNN_Keyframe \
/BLIO/KNN_Keyframe_map \
/BLIO/Keyframe_map_align \
/scout/mavros/vision_pose/pose \
/scout/mavros/local_position/pose \
/scout/mavros/local_position/odom \
/scout/mavros/setpoint_velocity/cmd_vel \
/scout/mavros/local_position/velocity_local \
/scout/mavros/manual_control/control \
/scout/mavros/manual_control/sen \
/scout/global_goal \
/scout/local_goal \
/scout/map \
/scout/map_distance \
/scout/map_check \
/tf \
/scout/astar_path_vis \
/scout/marker_target \
/scout/astar_path \
/scout/GoalAction \
/GoalPoint \
/Mission \
/scout/mavros/state \
/camera/color/image_raw/compressed \
/camera/color/camera_info \
/detection \
/detection_3d \
/detection_3d_pub \
/detections \
/detections_image \
/scout/mavros/setpoint_raw/attitude \
/scout/mavros/setpoint_raw/global \
/scout/mavros/setpoint_raw/local \
/scout/mavros/setpoint_raw/target_attitude \
/scout/mavros/setpoint_raw/target_global \
/scout/mavros/setpoint_raw/target_local \
/scout/teraranger_evo \
/global_path \
/delta_odom \
/ndt_odom \
/init_align_point \
/scout/command/current_reference \
/scout/command/current_reference_pose \
/scout/command/current_reference_twist \
/scout/full_predicted_state \
/scout/mavros/setpoint_raw/attitude \
/scout/predicted_state \
/scout/reference_trajectory \
/scout/state_machine/state_info \